// Sample content for the Learning Hub
window.LH_DATA = {
  signposts: [
    { type: 'Courses', icon: 'school', count: 42, desc: 'Master essential GRC topics through targeted short courses.', href: 'index.html#courses' },
    { type: 'Templates', icon: 'description', count: 68, desc: 'Access professionally crafted and ready-to-use templates that accelerate your governance initiatives.', href: 'index.html#templates' },
    { type: 'Videos', icon: 'play_circle', count: 120, desc: 'Watch interviews with industry experts and animated content breaking down complex principles into digestible, memorable formats.', href: 'index.html#videos' },
    { type: 'Learning Paths', icon: 'route', count: 14, desc: 'Access curated sets of content on a given topic, helping you build skills with clarity and confidence.', href: 'index.html#paths' },
  ],
  popular: [
    { id: 'C-231', type: 'Course', title: 'The modern board: governance in a volatile era', desc: 'Core principles and practical frameworks for directors navigating macro uncertainty.', tier: 'Free', subjects: ['Governance', 'Strategy'], duration: '45 min', href: 'course.html', image: 'assets/courses/key-roles-corporate-governance.png' },
    { id: 'T-118', type: 'Template', title: 'Board risk appetite statement — working draft', desc: 'Editable template with guidance notes, covering quantitative and qualitative indicators.', tier: 'Gated', subjects: ['Risk', 'Templates'], duration: 'Download', href: 'template.html', image: 'assets/templates/anti-money-laundering.png' },
    { id: 'V-074', type: 'Video', title: 'Inside the audit committee: a year in the chair', desc: 'Thirty-minute conversation with three chairs on running effective audit committees.', tier: 'Premium', subjects: ['Audit'], duration: '32 min', href: 'course.html', image: 'assets/videos/cybersecurity-kpis.png' },
  ],
  newest: [
    { id: 'C-248', type: 'Course', title: 'AI oversight for non-executive directors', desc: 'Understand AI risk, ethics and emerging regulation — without the jargon.', tier: 'Premium', subjects: ['AI', 'Ethics'], duration: '60 min', href: 'course.html', image: 'assets/courses/ai-ethics-thought-experiment.png' },
    { id: 'L-021', type: 'Learning Path', title: 'New director onboarding, 30 days', desc: 'A structured path through the first month: fiduciary duties, meetings, committees.', tier: 'Gated', subjects: ['Onboarding'], duration: '8 items', href: 'learning-path.html', image: 'assets/learning-paths/becoming-board-ready.png' },
    { id: 'T-124', type: 'Template', title: 'Cyber incident response board briefing', desc: 'Pre-drafted briefing structure for your next cyber-focused board discussion.', tier: 'Free', subjects: ['Cyber'], duration: 'Download', href: 'template.html', image: 'assets/templates/audit-committees-glossary.png' },
  ],
  partners: [
    { name: 'Compensia', image: 'assets/partners/compensia.png' },
    { name: 'CRMG', image: 'assets/partners/crmg.png' },
    { name: 'Ethics & Boards', image: 'assets/partners/ethics-and-boards.png' },
    { name: 'Global Data Innovation', image: 'assets/partners/global-data-innovation.jpg?v=2' },
    { name: 'Goodwin', image: 'assets/partners/goodwin.jpg' },
    { name: 'Kirkland & Ellis', image: 'assets/partners/kirkland-and-ellis.png' },
    { name: 'Security Scorecard', image: 'assets/partners/security-scorecard.jpg' },
    { name: 'Sidley', image: 'assets/partners/sidley.jpg' },
    { name: 'Spencer Stuart', image: 'assets/partners/spencer-stuart.jpg' },
    { name: 'Taylor Wessing', image: 'assets/partners/taylor-wessing.jpg' },
    { name: 'Volkov Law', image: 'assets/partners/volkov-law.jpg' },
  ],
  library: [
    { id: 'C-231', type: 'Course', title: 'AI Ethics Thought Experiment: Manufacturing', desc: 'A scenario-based course exploring AI ethics dilemmas in industrial contexts.', tier: 'Free', subjects: ['AI', 'ERM', 'Public company'], personas: ['Board director', 'Risk'], regions: ['Global', 'USA'], duration: '45 min', image: 'assets/courses/ai-ethics-thought-experiment.png' },
    { id: 'T-118', type: 'Template', title: 'AI Ethics Board Agenda and Discussion Template', desc: 'Structured agenda and discussion guide for AI ethics oversight at the board level.', tier: 'Gated', subjects: ['AI', 'Agendas', 'Board committees'], personas: ['Company secretary', 'Board director'], regions: ['Global', 'EU'], duration: 'Download', image: 'assets/templates/ai-ethics-board-agenda.png' },
    { id: 'V-074', type: 'Video', title: '5 Common Cybersecurity KPIs', desc: 'Measuring and assessing cyber risk — practical metrics for board oversight.', tier: 'Premium', subjects: ['Cybersecurity', 'ERM', 'Public company'], personas: ['Risk', 'Executive management'], regions: ['USA', 'UK'], duration: '32 min', image: 'assets/videos/cybersecurity-kpis.png' },
    { id: 'L-014', type: 'Learning Path', title: 'AI Use in Governance', desc: 'A multi-module path on integrating AI into governance practice responsibly.', tier: 'Gated', subjects: ['AI', 'Board governance'], personas: ['Practitioner', 'Board director'], regions: ['Global', 'APAC'], duration: '6 items', image: 'assets/learning-paths/ai-use-in-governance.png' },
    { id: 'C-203', type: 'Course', title: 'Key Roles in Corporate Governance', desc: 'Understand the responsibilities and interplay of directors, officers and committees.', tier: 'Free', subjects: ['Board governance', 'Structure', 'Public company'], personas: ['Board director', 'General counsel'], regions: ['Global', 'USA'], duration: '40 min', image: 'assets/courses/key-roles-corporate-governance.png' },
    { id: 'T-102', type: 'Template', title: 'Anti-Money Laundering Policy Template (US)', desc: 'Comprehensive AML policy framework aligned with US regulatory requirements.', tier: 'Free', subjects: ['Compliance', 'Public company'], personas: ['Legal', 'General counsel'], regions: ['USA'], duration: 'Download', image: 'assets/templates/anti-money-laundering.png' },
    { id: 'V-061', type: 'Video', title: '5 Key Outcomes of Board Evaluations', desc: 'How rigorous evaluations strengthen board performance and decision-making.', tier: 'Premium', subjects: ['Evaluations', 'Board governance'], personas: ['Board director', 'Executive management'], regions: ['UK', 'EU'], duration: '24 min', image: 'assets/videos/board-evaluations.png' },
    { id: 'C-221', type: 'Course', title: 'Mapping Board Skills', desc: 'A practical introduction to skills mapping and building a balanced board.', tier: 'Gated', subjects: ['Evaluations', 'Structure', 'Nonprofit'], personas: ['Board director', 'Company secretary'], regions: ['Global', 'UK'], duration: '90 min', image: 'assets/courses/mapping-board-skills.png' },
    { id: 'L-009', type: 'Learning Path', title: 'Becoming Board Ready', desc: 'A structured path preparing aspiring directors for their first board appointment.', tier: 'Premium', subjects: ['Director onboarding', 'Board governance'], personas: ['Board director', 'Practitioner'], regions: ['Global'], duration: '5 items', image: 'assets/learning-paths/becoming-board-ready.png' },
    { id: 'V-088', type: 'Video', title: 'An Introduction to Fiduciary Duty', desc: 'Developing risk management excellence — a primer for new directors.', tier: 'Free', subjects: ['Board governance', 'Director onboarding'], personas: ['Board director', 'Legal'], regions: ['USA', 'Global'], duration: '18 min', image: 'assets/videos/fiduciary-duty.png' },
    { id: 'T-145', type: 'Template', title: 'Audit Committees Terminology Glossary', desc: 'Definitive glossary of terms every audit committee member should know.', tier: 'Free', subjects: ['Board committees', 'Financials', 'Public company'], personas: ['Practitioner', 'Company secretary'], regions: ['Global', 'USA'], duration: 'Download', image: 'assets/templates/audit-committees-glossary.png' },
    { id: 'L-027', type: 'Learning Path', title: 'Compliance Policies (EU)', desc: 'Navigate the European compliance landscape with this comprehensive learning path.', tier: 'Gated', subjects: ['Compliance', 'Subsidiaries'], personas: ['Legal', 'General counsel'], regions: ['EU'], duration: '7 items', image: 'assets/learning-paths/compliance-policies-eu.png' },
    { id: 'C-256', type: 'Course', title: 'AI Ethics Thought Experiment: Healthcare', desc: 'A scenario-based companion course examining AI ethics in clinical settings.', tier: 'Premium', subjects: ['AI', 'Compliance', 'Nonprofit'], personas: ['Board director', 'Risk'], regions: ['Global', 'EU'], duration: '50 min', image: 'assets/courses/ai-ethics-thought-experiment.png' },
    { id: 'V-093', type: 'Video', title: 'Cybersecurity KPIs in Practice', desc: 'A working session unpacking the metrics boards should be tracking quarterly.', tier: 'Gated', subjects: ['Cybersecurity', 'Meetings'], personas: ['Risk', 'Executive management'], regions: ['APAC', 'USA'], duration: '28 min', image: 'assets/videos/cybersecurity-kpis.png' },
    { id: 'T-167', type: 'Template', title: 'AI Ethics Board Charter', desc: 'Companion charter to the agenda template — defining mandate, scope and review cadence.', tier: 'Premium', subjects: ['AI', 'Board committees', 'Private company'], personas: ['Company secretary', 'General counsel'], regions: ['UK', 'Global'], duration: 'Download', image: 'assets/templates/ai-ethics-board-agenda.png' },
  ],
  certifications: [
    { title: 'AI Ethics & Board Oversight Certification', image: 'assets/badges/ai-ethics.png', url: 'https://www.diligent.com/platform/ai-ethics-board-oversight-certification' },
    { title: 'Cyber Risk & Strategy Certification', image: 'assets/badges/cyber-risk.png', url: 'https://www.diligent.com/platform/cyber-risk-strategy-leadership-certification' },
    { title: 'Climate & Sustainability Strategy Certification', image: 'assets/badges/climate.png', url: 'https://www.diligent.com/platform/climate-and-sustainability-strategy-certification' },
    { title: 'Enterprise Risk Management Certification', image: 'assets/badges/enterprise-risk.png', url: 'https://www.diligent.com/platform/enterprise-risk-management-certification' },
    { title: 'Company Secretary Certification', image: 'assets/badges/company-secretary.png', url: '#' },
    { title: 'Human Capital, Compensation & Culture Certification', image: 'assets/badges/human-capital.png', url: 'https://www.diligent.com/platform/human-capital-compensation-and-culture-certificate' },
  ],
  filters: {
    'Content type': [
      { label: 'Course', count: 42 },
      { label: 'Template', count: 68 },
      { label: 'Video', count: 120 },
      { label: 'Learning Path', count: 14 },
    ],
    'Subject': {
      'Board leadership and operations': ['Board governance', 'Meetings', 'Structure', 'Agendas', 'Board committees', 'Evaluations', 'Director onboarding', 'Compensation', 'Financials', 'Minutes'],
      'Risk management': ['ERM', 'Cybersecurity', 'AI', 'ESG', 'Market risk'],
      'Regulations and compliance': ['Compliance', 'ESG', 'IPO'],
      'Entity management': ['Entity management', 'Subsidiaries'],
      'Organization type': ['Public company', 'Private company', 'Nonprofit'],
    },
    'Region': [
      { label: 'Global', count: 210 },
      { label: 'USA', count: 118 },
      { label: 'UK', count: 72 },
      { label: 'EU', count: 88 },
      { label: 'APAC', count: 62 },
    ],
    'Persona': [
      { label: 'Board director', count: 180 },
      { label: 'Executive management', count: 112 },
      { label: 'Company secretary', count: 96 },
      { label: 'General counsel', count: 58 },
      { label: 'Practitioner', count: 74 },
      { label: 'Risk', count: 62 },
      { label: 'Legal', count: 48 },
    ],
  },
};
