/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Feedback = {
  _id: string;
  _type: "feedback";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  contentItem?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "course";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "template";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "video";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "learningPath";
  };
  rating?: number;
  comment?: string;
  submittedAt?: string;
};

export type Redirect = {
  _id: string;
  _type: "redirect";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  source?: string;
  destination?: string;
  isPermanent?: boolean;
};

export type CertificationBadge = {
  _id: string;
  _type: "certificationBadge";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  url?: string;
  order?: number;
};

export type EducationalPartner = {
  _id: string;
  _type: "educationalPartner";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  logo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  url?: string;
  order?: number;
};

export type HubSettings = {
  _id: string;
  _type: "hubSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteTitle?: string;
  siteDescription?: string;
  demoCTAUrl?: string;
  heroHeading?: string;
  heroSubheading?: string;
  heroOverview?: string;
  popularSectionHeading?: string;
  partnersSectionHeading?: string;
  librarySectionHeading?: string;
  questionsSectionHeading?: string;
  questionsSectionBody?: string;
  certificationsSectionHeading?: string;
  certificationsSectionBody?: string;
  footerHeading?: string;
  footerBody?: string;
  footerCTAText?: string;
  privacyPolicyUrl?: string;
  ogImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type LearningPath = {
  _id: string;
  _type: "learningPath";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  previousSlug?: string;
  description?: string;
  items?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "course";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "template";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "video";
  }>;
  estimatedCompletionTime?: string;
  thumbnail?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  publishedAt?: string;
  accessTier?: "free" | "gated" | "premium";
  credlyBadgeId?: string;
  subjects?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "subject";
  }>;
  personas?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "persona";
  }>;
  regions?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "region";
  }>;
  relatedItems?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "course";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "template";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "video";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "learningPath";
  }>;
  archived?: boolean;
  viewCount?: number;
  seoTitle?: string;
  seoDescription?: string;
  ogImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Video = {
  _id: string;
  _type: "video";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  previousSlug?: string;
  vidyardEmbed?: string;
  description?: string;
  duration?: string;
  thumbnail?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  publishedAt?: string;
  accessTier?: "free" | "gated" | "premium";
  subjects?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "subject";
  }>;
  personas?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "persona";
  }>;
  regions?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "region";
  }>;
  relatedItems?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "course";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "template";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "video";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "learningPath";
  }>;
  archived?: boolean;
  viewCount?: number;
  seoTitle?: string;
  seoDescription?: string;
  ogImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Template = {
  _id: string;
  _type: "template";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  previousSlug?: string;
  description?: string;
  file?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    _type: "file";
  };
  thumbnail?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  publishedAt?: string;
  accessTier?: "free" | "gated" | "premium";
  subjects?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "subject";
  }>;
  personas?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "persona";
  }>;
  regions?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "region";
  }>;
  relatedItems?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "course";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "template";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "video";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "learningPath";
  }>;
  archived?: boolean;
  viewCount?: number;
  seoTitle?: string;
  seoDescription?: string;
  ogImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Course = {
  _id: string;
  _type: "course";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  previousSlug?: string;
  description?: string;
  scormCourseId?: string;
  thumbnail?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  author?: string;
  publishedAt?: string;
  estimatedDuration?: string;
  accessTier?: "free" | "gated" | "premium";
  subjects?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "subject";
  }>;
  personas?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "persona";
  }>;
  regions?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "region";
  }>;
  relatedItems?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "course";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "template";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "video";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "learningPath";
  }>;
  restricted?: boolean;
  accessToken?: string;
  restrictedAccessNote?: string;
  archived?: boolean;
  viewCount?: number;
  seoTitle?: string;
  seoDescription?: string;
  ogImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Subject = {
  _id: string;
  _type: "subject";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  group?: "board-leadership-operations" | "risk-management" | "regulations-compliance" | "entity-management" | "organization-type";
};

export type Region = {
  _id: string;
  _type: "region";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
};

export type Persona = {
  _id: string;
  _type: "persona";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes = Feedback | Redirect | CertificationBadge | EducationalPartner | HubSettings | LearningPath | Video | Template | Course | Subject | Region | Persona | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageHotspot | SanityImageCrop | SanityFileAsset | SanityImageAsset | SanityImageMetadata | Geopoint | Slug | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./sanity/lib/queries.ts
// Variable: allContentItemsQuery
// Query: *[  _type in ["course", "template", "video", "learningPath"]  && !(_id in path("drafts.**"))  && archived != true  && (_type != "course" || restricted != true)] | order(publishedAt desc) {      _id,  _type,  title,  "slug": slug.current,  description,  thumbnail,  accessTier,  "subjects": subjects[]->{ _id, title, group },  "personas": personas[]->{ _id, title },  "regions": regions[]->{ _id, title },  publishedAt,  archived  }
export type AllContentItemsQueryResult = Array<{
  _id: string;
  _type: "course";
  title: string | null;
  slug: string | null;
  description: string | null;
  thumbnail: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  accessTier: "free" | "gated" | "premium" | null;
  subjects: Array<{
    _id: string;
    title: string | null;
    group: "board-leadership-operations" | "entity-management" | "organization-type" | "regulations-compliance" | "risk-management" | null;
  }> | null;
  personas: Array<{
    _id: string;
    title: string | null;
  }> | null;
  regions: Array<{
    _id: string;
    title: string | null;
  }> | null;
  publishedAt: string | null;
  archived: boolean | null;
} | {
  _id: string;
  _type: "learningPath";
  title: string | null;
  slug: string | null;
  description: string | null;
  thumbnail: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  accessTier: "free" | "gated" | "premium" | null;
  subjects: Array<{
    _id: string;
    title: string | null;
    group: "board-leadership-operations" | "entity-management" | "organization-type" | "regulations-compliance" | "risk-management" | null;
  }> | null;
  personas: Array<{
    _id: string;
    title: string | null;
  }> | null;
  regions: Array<{
    _id: string;
    title: string | null;
  }> | null;
  publishedAt: string | null;
  archived: boolean | null;
} | {
  _id: string;
  _type: "template";
  title: string | null;
  slug: string | null;
  description: string | null;
  thumbnail: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  accessTier: "free" | "gated" | "premium" | null;
  subjects: Array<{
    _id: string;
    title: string | null;
    group: "board-leadership-operations" | "entity-management" | "organization-type" | "regulations-compliance" | "risk-management" | null;
  }> | null;
  personas: Array<{
    _id: string;
    title: string | null;
  }> | null;
  regions: Array<{
    _id: string;
    title: string | null;
  }> | null;
  publishedAt: string | null;
  archived: boolean | null;
} | {
  _id: string;
  _type: "video";
  title: string | null;
  slug: string | null;
  description: string | null;
  thumbnail: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  accessTier: "free" | "gated" | "premium" | null;
  subjects: Array<{
    _id: string;
    title: string | null;
    group: "board-leadership-operations" | "entity-management" | "organization-type" | "regulations-compliance" | "risk-management" | null;
  }> | null;
  personas: Array<{
    _id: string;
    title: string | null;
  }> | null;
  regions: Array<{
    _id: string;
    title: string | null;
  }> | null;
  publishedAt: string | null;
  archived: boolean | null;
}>;
// Variable: hubSettingsQuery
// Query: *[_type == "hubSettings"][0]{    siteTitle,    siteDescription,    demoCTAUrl,    heroHeading,    heroSubheading,    heroOverview,    popularSectionHeading,    partnersSectionHeading,    librarySectionHeading,    questionsSectionHeading,    questionsSectionBody,    certificationsSectionHeading,    certificationsSectionBody,    footerHeading,    footerBody,    footerCTAText,    privacyPolicyUrl  }
export type HubSettingsQueryResult = {
  siteTitle: string | null;
  siteDescription: string | null;
  demoCTAUrl: string | null;
  heroHeading: string | null;
  heroSubheading: string | null;
  heroOverview: string | null;
  popularSectionHeading: string | null;
  partnersSectionHeading: string | null;
  librarySectionHeading: string | null;
  questionsSectionHeading: string | null;
  questionsSectionBody: string | null;
  certificationsSectionHeading: string | null;
  certificationsSectionBody: string | null;
  footerHeading: string | null;
  footerBody: string | null;
  footerCTAText: string | null;
  privacyPolicyUrl: string | null;
} | null;
// Variable: newestContentQuery
// Query: *[  _type in ["course", "template", "video", "learningPath"]  && !(_id in path("drafts.**"))  && archived != true  && (_type != "course" || restricted != true)] | order(publishedAt desc)[0...3] {      _id,  _type,  title,  "slug": slug.current,  description,  thumbnail,  accessTier,  "subjects": subjects[]->{ _id, title, group },  "personas": personas[]->{ _id, title },  "regions": regions[]->{ _id, title },  publishedAt,  archived  }
export type NewestContentQueryResult = Array<{
  _id: string;
  _type: "course";
  title: string | null;
  slug: string | null;
  description: string | null;
  thumbnail: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  accessTier: "free" | "gated" | "premium" | null;
  subjects: Array<{
    _id: string;
    title: string | null;
    group: "board-leadership-operations" | "entity-management" | "organization-type" | "regulations-compliance" | "risk-management" | null;
  }> | null;
  personas: Array<{
    _id: string;
    title: string | null;
  }> | null;
  regions: Array<{
    _id: string;
    title: string | null;
  }> | null;
  publishedAt: string | null;
  archived: boolean | null;
} | {
  _id: string;
  _type: "learningPath";
  title: string | null;
  slug: string | null;
  description: string | null;
  thumbnail: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  accessTier: "free" | "gated" | "premium" | null;
  subjects: Array<{
    _id: string;
    title: string | null;
    group: "board-leadership-operations" | "entity-management" | "organization-type" | "regulations-compliance" | "risk-management" | null;
  }> | null;
  personas: Array<{
    _id: string;
    title: string | null;
  }> | null;
  regions: Array<{
    _id: string;
    title: string | null;
  }> | null;
  publishedAt: string | null;
  archived: boolean | null;
} | {
  _id: string;
  _type: "template";
  title: string | null;
  slug: string | null;
  description: string | null;
  thumbnail: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  accessTier: "free" | "gated" | "premium" | null;
  subjects: Array<{
    _id: string;
    title: string | null;
    group: "board-leadership-operations" | "entity-management" | "organization-type" | "regulations-compliance" | "risk-management" | null;
  }> | null;
  personas: Array<{
    _id: string;
    title: string | null;
  }> | null;
  regions: Array<{
    _id: string;
    title: string | null;
  }> | null;
  publishedAt: string | null;
  archived: boolean | null;
} | {
  _id: string;
  _type: "video";
  title: string | null;
  slug: string | null;
  description: string | null;
  thumbnail: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  accessTier: "free" | "gated" | "premium" | null;
  subjects: Array<{
    _id: string;
    title: string | null;
    group: "board-leadership-operations" | "entity-management" | "organization-type" | "regulations-compliance" | "risk-management" | null;
  }> | null;
  personas: Array<{
    _id: string;
    title: string | null;
  }> | null;
  regions: Array<{
    _id: string;
    title: string | null;
  }> | null;
  publishedAt: string | null;
  archived: boolean | null;
}>;
// Variable: popularContentQuery
// Query: *[  _type in ["course", "template", "video", "learningPath"]  && !(_id in path("drafts.**"))  && archived != true  && (_type != "course" || restricted != true)] | order(viewCount desc, publishedAt desc)[0...3] {      _id,  _type,  title,  "slug": slug.current,  description,  thumbnail,  accessTier,  "subjects": subjects[]->{ _id, title, group },  "personas": personas[]->{ _id, title },  "regions": regions[]->{ _id, title },  publishedAt,  archived  }
export type PopularContentQueryResult = Array<{
  _id: string;
  _type: "course";
  title: string | null;
  slug: string | null;
  description: string | null;
  thumbnail: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  accessTier: "free" | "gated" | "premium" | null;
  subjects: Array<{
    _id: string;
    title: string | null;
    group: "board-leadership-operations" | "entity-management" | "organization-type" | "regulations-compliance" | "risk-management" | null;
  }> | null;
  personas: Array<{
    _id: string;
    title: string | null;
  }> | null;
  regions: Array<{
    _id: string;
    title: string | null;
  }> | null;
  publishedAt: string | null;
  archived: boolean | null;
} | {
  _id: string;
  _type: "learningPath";
  title: string | null;
  slug: string | null;
  description: string | null;
  thumbnail: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  accessTier: "free" | "gated" | "premium" | null;
  subjects: Array<{
    _id: string;
    title: string | null;
    group: "board-leadership-operations" | "entity-management" | "organization-type" | "regulations-compliance" | "risk-management" | null;
  }> | null;
  personas: Array<{
    _id: string;
    title: string | null;
  }> | null;
  regions: Array<{
    _id: string;
    title: string | null;
  }> | null;
  publishedAt: string | null;
  archived: boolean | null;
} | {
  _id: string;
  _type: "template";
  title: string | null;
  slug: string | null;
  description: string | null;
  thumbnail: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  accessTier: "free" | "gated" | "premium" | null;
  subjects: Array<{
    _id: string;
    title: string | null;
    group: "board-leadership-operations" | "entity-management" | "organization-type" | "regulations-compliance" | "risk-management" | null;
  }> | null;
  personas: Array<{
    _id: string;
    title: string | null;
  }> | null;
  regions: Array<{
    _id: string;
    title: string | null;
  }> | null;
  publishedAt: string | null;
  archived: boolean | null;
} | {
  _id: string;
  _type: "video";
  title: string | null;
  slug: string | null;
  description: string | null;
  thumbnail: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  accessTier: "free" | "gated" | "premium" | null;
  subjects: Array<{
    _id: string;
    title: string | null;
    group: "board-leadership-operations" | "entity-management" | "organization-type" | "regulations-compliance" | "risk-management" | null;
  }> | null;
  personas: Array<{
    _id: string;
    title: string | null;
  }> | null;
  regions: Array<{
    _id: string;
    title: string | null;
  }> | null;
  publishedAt: string | null;
  archived: boolean | null;
}>;
// Variable: educationalPartnersQuery
// Query: *[_type == "educationalPartner"] | order(order asc) {    _id,    name,    logo,    url  }
export type EducationalPartnersQueryResult = Array<{
  _id: string;
  name: string | null;
  logo: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  url: string | null;
}>;
// Variable: certificationBadgesQuery
// Query: *[_type == "certificationBadge"] | order(order asc) {    _id,    title,    image,    url  }
export type CertificationBadgesQueryResult = Array<{
  _id: string;
  title: string | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  url: string | null;
}>;
// Variable: allPersonasQuery
// Query: *[_type == "persona"] | order(title asc) {    _id,    title  }
export type AllPersonasQueryResult = Array<{
  _id: string;
  title: string | null;
}>;
// Variable: allRegionsQuery
// Query: *[_type == "region"] | order(title asc) {    _id,    title  }
export type AllRegionsQueryResult = Array<{
  _id: string;
  title: string | null;
}>;
// Variable: allSubjectsQuery
// Query: *[_type == "subject"] | order(group asc, title asc) {    _id,    title,    group  }
export type AllSubjectsQueryResult = Array<{
  _id: string;
  title: string | null;
  group: "board-leadership-operations" | "entity-management" | "organization-type" | "regulations-compliance" | "risk-management" | null;
}>;
// Variable: courseBySlugQuery
// Query: *[_type == "course" && slug.current == $slug && archived != true][0] {      _id,  _type,  title,  "slug": slug.current,  description,  thumbnail,  accessTier,  "subjects": subjects[]->{ _id, title, group },  "personas": personas[]->{ _id, title },  "regions": regions[]->{ _id, title },  publishedAt,  archived,    scormCourseId,    estimatedDuration,    author,    restricted,    restrictedAccessNote  }
export type CourseBySlugQueryResult = {
  _id: string;
  _type: "course";
  title: string | null;
  slug: string | null;
  description: string | null;
  thumbnail: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  accessTier: "free" | "gated" | "premium" | null;
  subjects: Array<{
    _id: string;
    title: string | null;
    group: "board-leadership-operations" | "entity-management" | "organization-type" | "regulations-compliance" | "risk-management" | null;
  }> | null;
  personas: Array<{
    _id: string;
    title: string | null;
  }> | null;
  regions: Array<{
    _id: string;
    title: string | null;
  }> | null;
  publishedAt: string | null;
  archived: boolean | null;
  scormCourseId: string | null;
  estimatedDuration: string | null;
  author: string | null;
  restricted: boolean | null;
  restrictedAccessNote: string | null;
} | null;
// Variable: templateBySlugQuery
// Query: *[_type == "template" && slug.current == $slug && archived != true][0] {      _id,  _type,  title,  "slug": slug.current,  description,  thumbnail,  accessTier,  "subjects": subjects[]->{ _id, title, group },  "personas": personas[]->{ _id, title },  "regions": regions[]->{ _id, title },  publishedAt,  archived,    file  }
export type TemplateBySlugQueryResult = {
  _id: string;
  _type: "template";
  title: string | null;
  slug: string | null;
  description: string | null;
  thumbnail: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  accessTier: "free" | "gated" | "premium" | null;
  subjects: Array<{
    _id: string;
    title: string | null;
    group: "board-leadership-operations" | "entity-management" | "organization-type" | "regulations-compliance" | "risk-management" | null;
  }> | null;
  personas: Array<{
    _id: string;
    title: string | null;
  }> | null;
  regions: Array<{
    _id: string;
    title: string | null;
  }> | null;
  publishedAt: string | null;
  archived: boolean | null;
  file: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    _type: "file";
  } | null;
} | null;
// Variable: videoBySlugQuery
// Query: *[_type == "video" && slug.current == $slug && archived != true][0] {      _id,  _type,  title,  "slug": slug.current,  description,  thumbnail,  accessTier,  "subjects": subjects[]->{ _id, title, group },  "personas": personas[]->{ _id, title },  "regions": regions[]->{ _id, title },  publishedAt,  archived,    vidyardEmbed,    duration  }
export type VideoBySlugQueryResult = {
  _id: string;
  _type: "video";
  title: string | null;
  slug: string | null;
  description: string | null;
  thumbnail: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  accessTier: "free" | "gated" | "premium" | null;
  subjects: Array<{
    _id: string;
    title: string | null;
    group: "board-leadership-operations" | "entity-management" | "organization-type" | "regulations-compliance" | "risk-management" | null;
  }> | null;
  personas: Array<{
    _id: string;
    title: string | null;
  }> | null;
  regions: Array<{
    _id: string;
    title: string | null;
  }> | null;
  publishedAt: string | null;
  archived: boolean | null;
  vidyardEmbed: string | null;
  duration: string | null;
} | null;
// Variable: learningPathBySlugQuery
// Query: *[_type == "learningPath" && slug.current == $slug && archived != true][0] {      _id,  _type,  title,  "slug": slug.current,  description,  thumbnail,  accessTier,  "subjects": subjects[]->{ _id, title, group },  "personas": personas[]->{ _id, title },  "regions": regions[]->{ _id, title },  publishedAt,  archived,    estimatedCompletionTime,    credlyBadgeId,    items[]->{   _id,  _type,  title,  "slug": slug.current,  description,  thumbnail,  accessTier,  "subjects": subjects[]->{ _id, title, group },  "personas": personas[]->{ _id, title },  "regions": regions[]->{ _id, title },  publishedAt,  archived }  }
export type LearningPathBySlugQueryResult = {
  _id: string;
  _type: "learningPath";
  title: string | null;
  slug: string | null;
  description: string | null;
  thumbnail: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  accessTier: "free" | "gated" | "premium" | null;
  subjects: Array<{
    _id: string;
    title: string | null;
    group: "board-leadership-operations" | "entity-management" | "organization-type" | "regulations-compliance" | "risk-management" | null;
  }> | null;
  personas: Array<{
    _id: string;
    title: string | null;
  }> | null;
  regions: Array<{
    _id: string;
    title: string | null;
  }> | null;
  publishedAt: string | null;
  archived: boolean | null;
  estimatedCompletionTime: string | null;
  credlyBadgeId: string | null;
  items: Array<{
    _id: string;
    _type: "course";
    title: string | null;
    slug: string | null;
    description: string | null;
    thumbnail: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
    accessTier: "free" | "gated" | "premium" | null;
    subjects: Array<{
      _id: string;
      title: string | null;
      group: "board-leadership-operations" | "entity-management" | "organization-type" | "regulations-compliance" | "risk-management" | null;
    }> | null;
    personas: Array<{
      _id: string;
      title: string | null;
    }> | null;
    regions: Array<{
      _id: string;
      title: string | null;
    }> | null;
    publishedAt: string | null;
    archived: boolean | null;
  } | {
    _id: string;
    _type: "template";
    title: string | null;
    slug: string | null;
    description: string | null;
    thumbnail: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
    accessTier: "free" | "gated" | "premium" | null;
    subjects: Array<{
      _id: string;
      title: string | null;
      group: "board-leadership-operations" | "entity-management" | "organization-type" | "regulations-compliance" | "risk-management" | null;
    }> | null;
    personas: Array<{
      _id: string;
      title: string | null;
    }> | null;
    regions: Array<{
      _id: string;
      title: string | null;
    }> | null;
    publishedAt: string | null;
    archived: boolean | null;
  } | {
    _id: string;
    _type: "video";
    title: string | null;
    slug: string | null;
    description: string | null;
    thumbnail: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
    accessTier: "free" | "gated" | "premium" | null;
    subjects: Array<{
      _id: string;
      title: string | null;
      group: "board-leadership-operations" | "entity-management" | "organization-type" | "regulations-compliance" | "risk-management" | null;
    }> | null;
    personas: Array<{
      _id: string;
      title: string | null;
    }> | null;
    regions: Array<{
      _id: string;
      title: string | null;
    }> | null;
    publishedAt: string | null;
    archived: boolean | null;
  }> | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n  *[\n  _type in [\"course\", \"template\", \"video\", \"learningPath\"]\n  && !(_id in path(\"drafts.**\"))\n  && archived != true\n  && (_type != \"course\" || restricted != true)\n] | order(publishedAt desc) {\n    \n  _id,\n  _type,\n  title,\n  \"slug\": slug.current,\n  description,\n  thumbnail,\n  accessTier,\n  \"subjects\": subjects[]->{ _id, title, group },\n  \"personas\": personas[]->{ _id, title },\n  \"regions\": regions[]->{ _id, title },\n  publishedAt,\n  archived\n\n  }\n": AllContentItemsQueryResult;
    "\n  *[_type == \"hubSettings\"][0]{\n    siteTitle,\n    siteDescription,\n    demoCTAUrl,\n    heroHeading,\n    heroSubheading,\n    heroOverview,\n    popularSectionHeading,\n    partnersSectionHeading,\n    librarySectionHeading,\n    questionsSectionHeading,\n    questionsSectionBody,\n    certificationsSectionHeading,\n    certificationsSectionBody,\n    footerHeading,\n    footerBody,\n    footerCTAText,\n    privacyPolicyUrl\n  }\n": HubSettingsQueryResult;
    "\n  *[\n  _type in [\"course\", \"template\", \"video\", \"learningPath\"]\n  && !(_id in path(\"drafts.**\"))\n  && archived != true\n  && (_type != \"course\" || restricted != true)\n] | order(publishedAt desc)[0...3] {\n    \n  _id,\n  _type,\n  title,\n  \"slug\": slug.current,\n  description,\n  thumbnail,\n  accessTier,\n  \"subjects\": subjects[]->{ _id, title, group },\n  \"personas\": personas[]->{ _id, title },\n  \"regions\": regions[]->{ _id, title },\n  publishedAt,\n  archived\n\n  }\n": NewestContentQueryResult;
    "\n  *[\n  _type in [\"course\", \"template\", \"video\", \"learningPath\"]\n  && !(_id in path(\"drafts.**\"))\n  && archived != true\n  && (_type != \"course\" || restricted != true)\n] | order(viewCount desc, publishedAt desc)[0...3] {\n    \n  _id,\n  _type,\n  title,\n  \"slug\": slug.current,\n  description,\n  thumbnail,\n  accessTier,\n  \"subjects\": subjects[]->{ _id, title, group },\n  \"personas\": personas[]->{ _id, title },\n  \"regions\": regions[]->{ _id, title },\n  publishedAt,\n  archived\n\n  }\n": PopularContentQueryResult;
    "\n  *[_type == \"educationalPartner\"] | order(order asc) {\n    _id,\n    name,\n    logo,\n    url\n  }\n": EducationalPartnersQueryResult;
    "\n  *[_type == \"certificationBadge\"] | order(order asc) {\n    _id,\n    title,\n    image,\n    url\n  }\n": CertificationBadgesQueryResult;
    "\n  *[_type == \"persona\"] | order(title asc) {\n    _id,\n    title\n  }\n": AllPersonasQueryResult;
    "\n  *[_type == \"region\"] | order(title asc) {\n    _id,\n    title\n  }\n": AllRegionsQueryResult;
    "\n  *[_type == \"subject\"] | order(group asc, title asc) {\n    _id,\n    title,\n    group\n  }\n": AllSubjectsQueryResult;
    "\n  *[_type == \"course\" && slug.current == $slug && archived != true][0] {\n    \n  _id,\n  _type,\n  title,\n  \"slug\": slug.current,\n  description,\n  thumbnail,\n  accessTier,\n  \"subjects\": subjects[]->{ _id, title, group },\n  \"personas\": personas[]->{ _id, title },\n  \"regions\": regions[]->{ _id, title },\n  publishedAt,\n  archived\n,\n    scormCourseId,\n    estimatedDuration,\n    author,\n    restricted,\n    restrictedAccessNote\n  }\n": CourseBySlugQueryResult;
    "\n  *[_type == \"template\" && slug.current == $slug && archived != true][0] {\n    \n  _id,\n  _type,\n  title,\n  \"slug\": slug.current,\n  description,\n  thumbnail,\n  accessTier,\n  \"subjects\": subjects[]->{ _id, title, group },\n  \"personas\": personas[]->{ _id, title },\n  \"regions\": regions[]->{ _id, title },\n  publishedAt,\n  archived\n,\n    file\n  }\n": TemplateBySlugQueryResult;
    "\n  *[_type == \"video\" && slug.current == $slug && archived != true][0] {\n    \n  _id,\n  _type,\n  title,\n  \"slug\": slug.current,\n  description,\n  thumbnail,\n  accessTier,\n  \"subjects\": subjects[]->{ _id, title, group },\n  \"personas\": personas[]->{ _id, title },\n  \"regions\": regions[]->{ _id, title },\n  publishedAt,\n  archived\n,\n    vidyardEmbed,\n    duration\n  }\n": VideoBySlugQueryResult;
    "\n  *[_type == \"learningPath\" && slug.current == $slug && archived != true][0] {\n    \n  _id,\n  _type,\n  title,\n  \"slug\": slug.current,\n  description,\n  thumbnail,\n  accessTier,\n  \"subjects\": subjects[]->{ _id, title, group },\n  \"personas\": personas[]->{ _id, title },\n  \"regions\": regions[]->{ _id, title },\n  publishedAt,\n  archived\n,\n    estimatedCompletionTime,\n    credlyBadgeId,\n    items[]->{ \n  _id,\n  _type,\n  title,\n  \"slug\": slug.current,\n  description,\n  thumbnail,\n  accessTier,\n  \"subjects\": subjects[]->{ _id, title, group },\n  \"personas\": personas[]->{ _id, title },\n  \"regions\": regions[]->{ _id, title },\n  publishedAt,\n  archived\n }\n  }\n": LearningPathBySlugQueryResult;
  }
}
